"""generate tables

Revision ID: 1d7556a4c375
Revises: 
Create Date: 2024-09-22 20:25:08.740544

"""
from alembic import op
import sqlalchemy as sa
from utils.customs import JSONEncodedList

# revision identifiers, used by Alembic.
revision = '1d7556a4c375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('national_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('passport', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('parent_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('providers',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('national_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('passport', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('role', sa.Enum('admin', 'reception_desk', 'accounts_desk'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vaccines',
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('composition', sa.String(), nullable=False),
    sa.Column('schedule', JSONEncodedList, nullable=False),
    sa.Column('indication', sa.String(), nullable=False),
    sa.Column('side_effects', JSONEncodedList, nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('vaccine_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_appointments_parent_id_parents')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name=op.f('fk_appointments_provider_id_providers')),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('children',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('certificate_No', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('passport', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_children_parent_id_parents')),
    sa.PrimaryKeyConstraint('child_id'),
    sa.UniqueConstraint('certificate_No')
    )
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('mode_of_delivery', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('duration_of_labour', sa.String(), nullable=False),
    sa.Column('condition_of_mother', sa.String(), nullable=False),
    sa.Column('condition_of_baby', sa.String(), nullable=False),
    sa.Column('birth_weight_at_birth', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_deliveries_parent_id_parents')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name=op.f('fk_deliveries_provider_id_providers')),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('discharge_medications',
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size_in_mg', sa.Integer(), nullable=True),
    sa.Column('dose_in_mg', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('dose_per_day', sa.String(), nullable=True),
    sa.Column('referral', sa.String(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_discharge_medications_parent_id_parents')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name=op.f('fk_discharge_medications_provider_id_providers')),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_table('discharge_summaries',
    sa.Column('discharge_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_diagnosis', sa.String(), nullable=False),
    sa.Column('procedure', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_discharge_summaries_parent_id_parents')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name=op.f('fk_discharge_summaries_provider_id_providers')),
    sa.PrimaryKeyConstraint('discharge_id')
    )
    op.create_table('parents_medical_info',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('blood_transfusion', sa.String(), nullable=True),
    sa.Column('family_history', sa.String(), nullable=True),
    sa.Column('twins', sa.String(), nullable=True),
    sa.Column('tuberclosis', sa.String(), nullable=True),
    sa.Column('diabetes', sa.String(), nullable=True),
    sa.Column('hypertension', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_parents_medical_info_parent_id_parents')),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_payments_parent_id_parents')),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('present_pregnancies',
    sa.Column('pp_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('weight_in_kg', sa.Integer(), nullable=False),
    sa.Column('urinalysis', sa.String(), nullable=False),
    sa.Column('blood_pressure', sa.String(), nullable=False),
    sa.Column('pollar', sa.String(), nullable=False),
    sa.Column('maturity_in_weeks', sa.Integer(), nullable=False),
    sa.Column('fundal_height', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=False),
    sa.Column('clinical_notes', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_present_pregnancies_parent_id_parents')),
    sa.PrimaryKeyConstraint('pp_id')
    )
    op.create_table('previous_pregnancies',
    sa.Column('pp_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('maturity', sa.String(), nullable=False),
    sa.Column('duration_of_labour', sa.String(), nullable=False),
    sa.Column('type_of_delivery', sa.String(), nullable=False),
    sa.Column('Weight_in_kg', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('fate', sa.String(), nullable=False),
    sa.Column('peurperium', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_previous_pregnancies_parent_id_parents')),
    sa.PrimaryKeyConstraint('pp_id')
    )
    op.create_table('resetokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_resetokens_parent_id_parents')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name=op.f('fk_resetokens_provider_id_providers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_resetokens_user_id_users')),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('lab_tests',
    sa.Column('lab_test_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], name=op.f('fk_lab_tests_child_id_children')),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_lab_tests_parent_id_parents')),
    sa.PrimaryKeyConstraint('lab_test_id')
    )
    op.create_table('vacination_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], name=op.f('fk_vacination_records_child_id_children')),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_vacination_records_parent_id_parents')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name=op.f('fk_vacination_records_provider_id_providers')),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccines.vaccine_id'], name=op.f('fk_vacination_records_vaccine_id_vaccines')),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacination_records')
    op.drop_table('lab_tests')
    op.drop_table('resetokens')
    op.drop_table('previous_pregnancies')
    op.drop_table('present_pregnancies')
    op.drop_table('payments')
    op.drop_table('parents_medical_info')
    op.drop_table('discharge_summaries')
    op.drop_table('discharge_medications')
    op.drop_table('deliveries')
    op.drop_table('children')
    op.drop_table('appointments')
    op.drop_table('vaccines')
    op.drop_table('users')
    op.drop_table('providers')
    op.drop_table('parents')
    # ### end Alembic commands ###
