"""added a constraint and assesment

Revision ID: 24cdd60d9163
Revises: 70f400bd20b7
Create Date: 2024-10-20 22:29:46.434084

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24cdd60d9163"
down_revision = "70f400bd20b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("general_assessment", sa.String(), nullable=True))
        batch_op.drop_column("nursing_assessment")
        batch_op.drop_column("physician_assessment")

    with op.batch_alter_table("beds", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_bed_number", ["bed_number"]
        )  # Added constraint name

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("beds", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_bed_number", type_="unique"
        )  # Use the constraint name

    with op.batch_alter_table("admissions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("physician_assessment", sa.VARCHAR(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("nursing_assessment", sa.VARCHAR(), nullable=True)
        )
        batch_op.drop_column("general_assessment")

    # ### end Alembic commands ###
