"""empty message

Revision ID: 38b81ea38d3f
Revises: e07ea2ff8c4f
Create Date: 2024-11-02 00:12:27.503559

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38b81ea38d3f"
down_revision = "e07ea2ff8c4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("births", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("fate", sa.String(), nullable=False, server_default="Unknown")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("births", schema=None) as batch_op:
        batch_op.drop_column("fate")

    # ### end Alembic commands ###
