"""subcounty and serial number

Revision ID: 649b7cec00f8
Revises: 7ebef4613828
Create Date: 2024-11-02 11:38:19.164801

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "649b7cec00f8"
down_revision = "7ebef4613828"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("births", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sub_county", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("serial_number", sa.Integer(), nullable=False))
        # Specify a name for the unique constraint
        batch_op.create_unique_constraint("uq_birth_serial_number", ["serial_number"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("births", schema=None) as batch_op:
        # Drop the unique constraint by name
        batch_op.drop_constraint("uq_birth_serial_number", type_="unique")
        batch_op.drop_column("serial_number")
        batch_op.drop_column("sub_county")

    # ### end Alembic commands ###
