"""Room and Bed tables and an update on Admisions table

Revision ID: 70f400bd20b7
Revises: 87aa8acf8b00
Create Date: 2024-10-20 16:55:18.669153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f400bd20b7'
down_revision = '87aa8acf8b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=True),
    sa.Column('current_bed_occupancy', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('facilities', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('beds',
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(), nullable=False),
    sa.Column('bed_type', sa.String(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_beds_room_id_rooms')),
    sa.PrimaryKeyConstraint('bed_id')
    )
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bed_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_admissions_bed_id_beds'), 'beds', ['bed_id'], ['bed_id'])
        batch_op.create_foreign_key(batch_op.f('fk_admissions_room_id_rooms'), 'rooms', ['room_id'], ['room_id'])
        batch_op.drop_column('room_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_number', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_admissions_room_id_rooms'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_admissions_bed_id_beds'), type_='foreignkey')
        batch_op.drop_column('bed_id')
        batch_op.drop_column('room_id')

    op.drop_table('beds')
    op.drop_table('rooms')
    # ### end Alembic commands ###
