"""updates

Revision ID: 7c67d11f613d
Revises: d7d89bc35bc0
Create Date: 2024-10-26 14:34:47.947902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c67d11f613d'
down_revision = 'd7d89bc35bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('births',
    sa.Column('birth_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('baby_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('place_of_birth', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('mother_full_name', sa.String(), nullable=False),
    sa.Column('mother_national_id', sa.String(), nullable=False),
    sa.Column('mother_age', sa.Integer(), nullable=True),
    sa.Column('mother_occupation', sa.String(), nullable=True),
    sa.Column('father_full_name', sa.String(), nullable=True),
    sa.Column('father_national_id', sa.String(), nullable=True),
    sa.Column('father_age', sa.Integer(), nullable=True),
    sa.Column('father_occupation', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('birth_attendant', sa.String(), nullable=True),
    sa.Column('date_of_notification', sa.DateTime(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.delivery_id'], name=op.f('fk_births_delivery_id_deliveries')),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_births_parent_id_parents')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name=op.f('fk_births_provider_id_providers')),
    sa.PrimaryKeyConstraint('birth_id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fate', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('remarks', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('present_pregnancy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_deliveries_present_pregnancy_id_present_pregnancies'), 'present_pregnancies', ['present_pregnancy_id'], ['pp_id'])

    with op.batch_alter_table('discharge_medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_discharge_medications_child_id_children'), 'children', ['child_id'], ['child_id'])

    with op.batch_alter_table('present_pregnancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_present_pregnancies_provider_id_providers'), 'providers', ['provider_id'], ['provider_id'])

    with op.batch_alter_table('previous_pregnancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_in_kg', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('puerperium', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_previous_pregnancies_delivery_id_deliveries'), 'deliveries', ['delivery_id'], ['delivery_id'])
        batch_op.create_foreign_key(batch_op.f('fk_previous_pregnancies_provider_id_providers'), 'providers', ['provider_id'], ['provider_id'])
        batch_op.drop_column('peurperium')
        batch_op.drop_column('Weight_in_kg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('previous_pregnancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Weight_in_kg', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('peurperium', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_previous_pregnancies_provider_id_providers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_previous_pregnancies_delivery_id_deliveries'), type_='foreignkey')
        batch_op.drop_column('delivery_id')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('puerperium')
        batch_op.drop_column('weight_in_kg')

    with op.batch_alter_table('present_pregnancies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_present_pregnancies_provider_id_providers'), type_='foreignkey')
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('discharge_medications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_discharge_medications_child_id_children'), type_='foreignkey')
        batch_op.drop_column('child_id')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_deliveries_present_pregnancy_id_present_pregnancies'), type_='foreignkey')
        batch_op.drop_column('present_pregnancy_id')
        batch_op.drop_column('remarks')
        batch_op.drop_column('fate')

    op.drop_table('births')
    # ### end Alembic commands ###
