"""type of birth to string

Revision ID: 7ebef4613828
Revises: 38b81ea38d3f
Create Date: 2024-11-02 07:13:00.567606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebef4613828'
down_revision = '38b81ea38d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.alter_column('type_of_birth',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.alter_column('type_of_birth',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
