"""medicine and prescriptions tables

Revision ID: 86f29e300328
Revises: 1d7556a4c375
Create Date: 2024-10-08 00:05:27.839950

"""

from alembic import op
import sqlalchemy as sa
from utils.customs import JSONEncodedList

# revision identifiers, used by Alembic.
revision = "86f29e300328"
down_revision = "1d7556a4c375"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medicines",
        sa.Column("medicine_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("composition", sa.String(), nullable=False),
        sa.Column("dosage", sa.String(), nullable=False),
        sa.Column("indication", sa.String(), nullable=False),
        sa.Column("side_effects", JSONEncodedList(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("medicine_id"),
    )
    op.create_table(
        "prescriptions",
        sa.Column("prescription_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.Column("medicine_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("dosage", sa.String(), nullable=False),
        sa.Column("duration", sa.String(), nullable=False),
        sa.Column("refill_count", sa.Integer(), nullable=False),
        sa.Column("filled_date", sa.DateTime(), nullable=True),
        sa.Column("expiry_date", sa.DateTime(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.child_id"],
            name=op.f("fk_prescriptions_child_id_children"),
        ),
        sa.ForeignKeyConstraint(
            ["medicine_id"],
            ["medicines.medicine_id"],
            name=op.f("fk_prescriptions_medicine_id_medicines"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.parent_id"],
            name=op.f("fk_prescriptions_parent_id_parents"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.provider_id"],
            name=op.f("fk_prescriptions_provider_id_providers"),
        ),
        sa.PrimaryKeyConstraint("prescription_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prescriptions")
    op.drop_table("medicines")
    # ### end Alembic commands ###
