"""discharge and admission tables

Revision ID: 87aa8acf8b00
Revises: 78cf60a65a65
Create Date: 2024-10-20 12:20:00.618675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87aa8acf8b00'
down_revision = '78cf60a65a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissions',
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('reason_for_admission', sa.String(), nullable=False),
    sa.Column('nursing_assessment', sa.String(), nullable=True),
    sa.Column('physician_assessment', sa.String(), nullable=True),
    sa.Column('initial_treatment_plan', sa.String(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=True),
    sa.Column('insurance_details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], name=op.f('fk_admissions_child_id_children')),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_admissions_parent_id_parents')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name=op.f('fk_admissions_provider_id_providers')),
    sa.PrimaryKeyConstraint('admission_id')
    )
    with op.batch_alter_table('discharge_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('child_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_discharge_summaries_child_id_children'), 'children', ['child_id'], ['child_id'])
        batch_op.create_foreign_key(batch_op.f('fk_discharge_summaries_admission_id_admissions'), 'admissions', ['admission_id'], ['admission_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discharge_summaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_discharge_summaries_admission_id_admissions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_discharge_summaries_child_id_children'), type_='foreignkey')
        batch_op.drop_column('child_id')
        batch_op.drop_column('admission_id')

    op.drop_table('admissions')
    # ### end Alembic commands ###
