"""kin columns and documents Table

Revision ID: 87bd9ce593ec
Revises: 86f29e300328
Create Date: 2024-10-09 09:24:16.403660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bd9ce593ec'
down_revision = '86f29e300328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entityType', sa.String(), nullable=False),
    sa.Column('documentType', sa.String(), nullable=False),
    sa.Column('fileName', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name=op.f('fk_documents_parent_id_parents')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], name=op.f('fk_documents_provider_id_providers')),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_of_kin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kin_phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kin_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kin_occupation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_column('kin_occupation')
        batch_op.drop_column('kin_email')
        batch_op.drop_column('kin_phone_number')
        batch_op.drop_column('next_of_kin')

    op.drop_table('documents')
    # ### end Alembic commands ###
