"""empty message

Revision ID: b43421054c57
Revises: ce525eb480ab
Create Date: 2024-10-29 16:23:55.452319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43421054c57'
down_revision = 'ce525eb480ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discharge_medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_discharge_medications_prescription_id_prescriptions'), 'prescriptions', ['prescription_id'], ['prescription_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discharge_medications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_discharge_medications_prescription_id_prescriptions'), type_='foreignkey')
        batch_op.drop_column('prescription_id')

    # ### end Alembic commands ###
