"""new column provider_id in table lab tests.


Revision ID: b5a99e8b3f09
Revises: 94b455e5d723
Create Date: 2024-10-17 10:30:01.316218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a99e8b3f09'
down_revision = '94b455e5d723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_lab_tests_provider_id_providers'), 'providers', ['provider_id'], ['provider_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lab_tests_provider_id_providers'), type_='foreignkey')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
