"""renamed a column in deliveries and upgraded from a downgraded version

Revision ID: c77f8a391b0c
Revises: 22d17ecfd028
Create Date: 2024-10-19 14:34:12.331385

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c77f8a391b0c"
down_revision = "22d17ecfd028"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.alter_column(
            "appointment_date",
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )

    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("weight_at_birth", sa.String(), nullable=True))
        batch_op.drop_column("birth_weight_at_birth")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("birth_weight_at_birth", sa.VARCHAR(), nullable=False)
        )
        batch_op.drop_column("weight_at_birth")

    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.alter_column(
            "appointment_date",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
