"""additional columns to track changes

Revision ID: ce525eb480ab
Revises: 880b6e0b6019
Create Date: 2024-10-29 11:36:19.609145

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ce525eb480ab"
down_revision = "880b6e0b6019"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admissions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_discharged",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false(),
            )
        )

    with op.batch_alter_table("births", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type_of_birth", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column(
                "is_registered",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false(),
            )
        )
        batch_op.drop_column("father_occupation")
        batch_op.drop_column("mother_age")
        batch_op.drop_column("father_age")
        batch_op.drop_column("marital_status")

    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type_of_birth", sa.Integer(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_read",
                sa.Boolean(),
                nullable=True,
                server_default=sa.sql.expression.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_replied",
                sa.Boolean(),
                nullable=True,
                server_default=sa.sql.expression.false(),
            )
        )
        batch_op.add_column(
            sa.Column("original_message_id", sa.Integer(), nullable=True)
        )
        batch_op.drop_column("isTermsAndCondition")
        batch_op.drop_column("isContactForm")

    with op.batch_alter_table("present_pregnancies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_delivered",
                sa.Boolean(),
                nullable=False,
                server_default=sa.sql.expression.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("present_pregnancies", schema=None) as batch_op:
        batch_op.drop_column("is_delivered")

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("isContactForm", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(
            sa.Column("isTermsAndCondition", sa.BOOLEAN(), nullable=True)
        )
        batch_op.drop_column("original_message_id")
        batch_op.drop_column("is_replied")
        batch_op.drop_column("is_read")

    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.drop_column("type_of_birth")

    with op.batch_alter_table("births", schema=None) as batch_op:
        batch_op.add_column(sa.Column("marital_status", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("father_age", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("mother_age", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("father_occupation", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("is_registered")
        batch_op.drop_column("type_of_birth")

    with op.batch_alter_table("admissions", schema=None) as batch_op:
        batch_op.drop_column("is_discharged")

    # ### end Alembic commands ###
