"""removed passport column

Revision ID: d7d89bc35bc0
Revises: 24cdd60d9163
Create Date: 2024-10-24 08:05:30.053071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d89bc35bc0'
down_revision = '24cdd60d9163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('passport')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
