"""empty message

Revision ID: e07ea2ff8c4f
Revises: e1609596a549
Create Date: 2024-11-01 14:56:38.617341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07ea2ff8c4f'
down_revision = 'e1609596a549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.drop_column('mother_occupation')
        batch_op.drop_column('birth_attendant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_attendant', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('mother_occupation', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
