"""empty message

Revision ID: e1609596a549
Revises: b43421054c57
Create Date: 2024-10-30 08:04:50.400214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1609596a549'
down_revision = 'b43421054c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discharge_medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medicine_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_discharge_medications_medicine_id_medicines'), 'medicines', ['medicine_id'], ['medicine_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discharge_medications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_discharge_medications_medicine_id_medicines'), type_='foreignkey')
        batch_op.drop_column('medicine_id')

    # ### end Alembic commands ###
