"""added child column for documents

Revision ID: f6e09f003f80
Revises: edc2d16de46a
Create Date: 2024-10-14 20:05:37.444033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e09f003f80'
down_revision = 'edc2d16de46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_documents_child_id_children'), 'children', ['child_id'], ['child_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_child_id_children'), type_='foreignkey')
        batch_op.drop_column('child_id')

    # ### end Alembic commands ###
